import { Injectable, signal } from '@angular/core';

/**
 * IATA code → IANA time zone, from public/data/airports.json (generated by
 * scripts/gen-airports.js). Loaded once, lazily, the first time a flight
 * time needs its zone; `zones()` is a signal so computeds re-run when it lands.
 */
@Injectable({ providedIn: 'root' })
export class AirportZoneService {
  readonly zones = signal<Record<string, string>>({});
  private loading = false;

  /** The zone for an airport code, or undefined while loading / when unknown. Triggers the load. */
  zoneFor(iata: string | undefined): string | undefined {
    if (!iata) return undefined;
    const z = this.zones()[iata.toUpperCase()];
    if (!z && !this.loading) this.load();
    return z;
  }

  private load(): void {
    this.loading = true;
    fetch('/data/airports.json').then(r => r.ok ? r.json() : {}).then(map => this.zones.set(map))
      .catch(() => { /* flights fall back to the trip's zone */ });
  }
}
