#!/usr/bin/env node
/**
 * Writes public/pulse/zones.mjs: every IANA zone the browser may report,
 * with the city it is named after, the US state where that applies, and the
 * country, from @vvo/tzdb. Run after `npm i -D @vvo/tzdb@latest` when zones
 * change (rarely):  node scripts/gen-zones.js
 */
const fs = require('fs');
const path = require('path');
const { rawTimeZones } = require('@vvo/tzdb');

const COUNTRY_SHORT = { 'United States': 'USA', 'United Kingdom': 'UK', 'United Arab Emirates': 'UAE' };
const US_STATE = {
  'America/New_York': 'New York', 'America/Detroit': 'Michigan', 'America/Kentucky/Louisville': 'Kentucky', 'America/Kentucky/Monticello': 'Kentucky',
  'America/Indiana/Indianapolis': 'Indiana', 'America/Indiana/Vincennes': 'Indiana', 'America/Indiana/Winamac': 'Indiana', 'America/Indiana/Marengo': 'Indiana',
  'America/Indiana/Petersburg': 'Indiana', 'America/Indiana/Vevay': 'Indiana', 'America/Indiana/Tell_City': 'Indiana', 'America/Indiana/Knox': 'Indiana',
  'America/Chicago': 'Illinois', 'America/Menominee': 'Michigan', 'America/North_Dakota/Center': 'North Dakota', 'America/North_Dakota/New_Salem': 'North Dakota',
  'America/North_Dakota/Beulah': 'North Dakota', 'America/Denver': 'Colorado', 'America/Boise': 'Idaho', 'America/Phoenix': 'Arizona',
  'America/Los_Angeles': 'California', 'America/Anchorage': 'Alaska', 'America/Juneau': 'Alaska', 'America/Sitka': 'Alaska', 'America/Metlakatla': 'Alaska',
  'America/Yakutat': 'Alaska', 'America/Nome': 'Alaska', 'America/Adak': 'Alaska', 'Pacific/Honolulu': 'Hawaii',
};
const cityOf = name => name.split('/').pop().replace(/_/g, ' ');

const zones = {};
for (const z of rawTimeZones) {
  for (const name of new Set([z.name, ...(z.group || [])])) {
    if (!name.includes('/') || /^(Etc|SystemV|US|Canada|Brazil|Mexico|Chile)\//.test(name)) continue;
    zones[name] = {
      city: name === z.name ? (z.mainCities[0] || cityOf(name)) : cityOf(name),
      region: US_STATE[name] || '',
      country: COUNTRY_SHORT[z.countryName] || z.countryName,
    };
  }
}
const out = path.join(__dirname, '..', 'public', 'pulse', 'zones.mjs');
fs.writeFileSync(out, `// Generated by scripts/gen-zones.js from @vvo/tzdb — do not edit.\n// IANA zone → { city, region (US state), country }.\nexport const ZONES = ${JSON.stringify(zones)};\n`);
console.log(`wrote ${path.relative(process.cwd(), out)}: ${Object.keys(zones).length} zones`);
