#!/usr/bin/env node
/**
 * gen-env.js
 *
 * Reads .env and generates src/environments/environment.ts and environment.prod.ts.
 * Run once after cloning, or any time .env changes.
 *
 * Usage:  node scripts/gen-env.js
 *         npm run gen-env
 */
const fs   = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '../.env');
if (!fs.existsSync(envPath)) {
  console.error(`ERROR: .env not found at ${envPath}`);
  console.error('Copy .env.example to .env and fill in the values.');
  process.exit(1);
}

// Parse .env
const env = {};
for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const [key, ...rest] = trimmed.split('=');
  env[key.trim()] = rest.join('=').trim();
}

const required = [
  'FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET', 'FIREBASE_MESSAGING_SENDER_ID', 'FIREBASE_APP_ID',
];
const missing = required.filter(k => !env[k]);
if (missing.length) {
  console.error(`ERROR: Missing required keys in .env: ${missing.join(', ')}`);
  process.exit(1);
}

const firebaseConfig = `{
    apiKey:            '${env.FIREBASE_API_KEY}',
    authDomain:        '${env.FIREBASE_AUTH_DOMAIN}',
    projectId:         '${env.FIREBASE_PROJECT_ID}',
    storageBucket:     '${env.FIREBASE_STORAGE_BUCKET}',
    messagingSenderId: '${env.FIREBASE_MESSAGING_SENDER_ID}',
    appId:             '${env.FIREBASE_APP_ID}',
  }`;

const devEnv = `// AUTO-GENERATED by scripts/gen-env.js — do not edit manually, do not commit
export const environment = {
  production: false,
  firebase: ${firebaseConfig},
};
`;

const prodEnv = `// AUTO-GENERATED by scripts/gen-env.js — do not edit manually, do not commit
export const environment = {
  production: true,
  firebase: ${firebaseConfig},
};
`;

const dir = path.join(__dirname, '../src/environments');
fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(path.join(dir, 'environment.ts'), devEnv);
fs.writeFileSync(path.join(dir, 'environment.prod.ts'), prodEnv);
console.log('✓ environment.ts and environment.prod.ts generated from .env');
